name: ContainerProtect
version: 1.0
main: com.nisipeanu.containerprotect.PluginMain
website: ggez.ro
api-version: 1.16
commands:
  cinfo:
    description: See protection info for a container
    usage: /<command>
    permission: containerprotect.info
  cprivate:
    description: Register a private container
    usage: /<command>
    permission: containerprotect.private
  cmodify:
    description: Allow someone to access a container
    usage: /<command> <target>
    permission: containerprotect.modify
  cremove:
    description: Remove private protection from a container
    usage: /<command>
    permission: containerprotect.remove
  creload:
    description: Reload the config
    usage: /<command>
    permission: containerprotect.reload
