name: ContainerProtect
version: 1.0
main: com.nisipeanu.containerprotect.PluginMain
website: ggez.ro
api-version: 1.16
commands:
  cinfo:
    description: See protection info for a container
    usage: /<command>
    permission: containerprotect.info
  cprivate:
    description: Register a private container
    usage: /<command>
    permission: containerprotect.private
  cmodify:
    description: Allow someone to access a container
    usage: /<command> <target>
    permission: containerprotect.modify
  cremove:
    description: Remove private protection from a container
    usage: /<command>
    permission: containerprotect.remove
  creload:
    description: Reload the config
    usage: /<command>
    permission: containerprotect.admin.reload
permissions:
  containerprotect.info:
    description: Can see information about a protection
    default: true
  containerprotect.private:
    description: Can register a private container
    default: true
  containerprotect.modify:
    description: Can add another player to own protection
    default: true
  containerprotect.remove:
    description: Can remove it's own private container
    default: true
  containerprotect.admin.reload:
    description: Can reload the config
    default: op
  containerprotect.admin.remove:
    description: Can remove someone else's protection
    default: op
  containerprotect.admin.interact:
    description: Can access someone else's protection
    default: op
