# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and release plugin

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.tag_name }}
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Update version in plugin.yml
      uses: fjogeleit/yaml-update-action@master
      with:
        valueFile: 'src/main/resources/plugin.yml'
        propertyPath: 'version'
        value: ${{ github.event.release.tag_name }}
        commitChange: false
        updateFile: true
    - name: Update version in pom.xml
      uses: Mudlet/xmlstarlet-action@master
      with:
        args: edit --inplace -N p=http://maven.apache.org/POM/4.0.0 -u "/p:project/p:version" -v "${{ github.event.release.tag_name }}" pom.xml
    - name: Build with Maven
      run: mvn package -f pom.xml
    - name: Attach files to release
      run: gh release upload ${{ github.event.release.tag_name }} target/ContainerProtect-*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
