# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and release plugin

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn package -f pom.xml
    - name: Attach files to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: target/ContainerProtect-*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
